### ISSUE TITLE
html output?

### ISSUE THREAD

**Issue by hasufell** [mgajda/homplexity#23]
I think it's common to have html output and run linters on e.g. jenkins, publishing the results for your team.

**Comment by mgajda** [comment]
Excellent idea!

Adding both HTML and Java Unit output should be easy.
Using builder like `blaze-html`, you would just need:
1. Add printing function for `Language.Haskell.Homplexity.Message.Message`
```
instance ToMarkup Message where ...
```
2. Add `--html` output flag to `app/Homplexity.hs`, and pass it to `analyzeModule` function:
```
data OutputFormat =
    Text
  | HTML

defineFlag "format" Text
```
3. Inside `analyzeModule` you need to replace `concatMap show` with appropriate showing function.
