### ISSUE TITLE
Fails to install

### ISSUE THREAD

**Issue by pjljvandelaar** [mgajda/homplexity#3]
I get the follow error message when trying to install homplexity

c:\TorXakisSandbox\1897_ImproveDesign\new\torxakis>cabal install homplexity
Warning: The package list for 'hackage.haskell.org' is 23 days old.
Run 'cabal update' to get the latest list of available packages.
Resolving dependencies...
Configuring homplexity-0.4.3.4...
Building homplexity-0.4.3.4...
Preprocessing executable 'homplexity' for homplexity-0.4.3.4...
[ 1 of 10] Compiling Language.Haskell.Homplexity.SrcSlice ( Language\Haskell\Homplexity\SrcS
lice.hs, dist\build\homplexity\homplexity-tmp\Language\Haskell\Homplexity\SrcSlice.o )
[ 2 of 10] Compiling Language.Haskell.Homplexity.Message ( Language\Haskell\Homplexity\Messa
ge.hs, dist\build\homplexity\homplexity-tmp\Language\Haskell\Homplexity\Message.o )
[ 3 of 10] Compiling Language.Haskell.Homplexity.CodeFragment ( Language\Haskell\Homplexity\
CodeFragment.hs, dist\build\homplexity\homplexity-tmp\Language\Haskell\Homplexity\CodeFragme
nt.o )

Language\Haskell\Homplexity\CodeFragment.hs:50:13:
    Not in scope: type constructor or class `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:51:13:
    Not in scope: data constructor `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:64:14:
    Not in scope: type constructor or class `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:65:14:
    Not in scope: data constructor `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:75:19:
    Not in scope: type constructor or class `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:76:19:
    Not in scope: data constructor `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:140:45:
    Not in scope: type constructor or class `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:147:48:
    Not in scope: type constructor or class `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:162:12:
    Not in scope: type constructor or class `Proxy'

Language\Haskell\Homplexity\CodeFragment.hs:163:12:
    Not in scope: data constructor `Proxy'
Failed to install homplexity-0.4.3.4
cabal: Error: some packages failed to install:
homplexity-0.4.3.4 failed during the building phase. The exception was:
ExitFailure 1

**Comment by PierreVDL** [comment]
Same error at different location!

My configuration:
- The Glorious Glasgow Haskell Compilation System, version 7.6.3
- Happy Version 1.19.5 Copyright (c) 1993-1996 Andy Gill, Simon Marlow (c) 1997-2005 Simon Mar
  low

**Comment by dnadales** [comment]
@pjljvandelaar try building with stack. I managed to build this using resolver `lts-8.24`, you might want to try:

```text
stack init
```

I built in on Linux though, so I don't know if this will work on your case. All in all, bear in mind that you might run into https://github.com/mgajda/homplexity/issues/5 (as I did).

**Comment by pjljvandelaar** [comment]
Cloning the archive and running `stack install` shows that the dependency on happy is not well managed:
```
    Configuring haskell-src-exts-1.18.2...
    Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe: The program 'happy' version
    >=1.19 is required but the version found at C:\Program Files (x86)\Haskell
    Platform\2013.2.0.0\lib\extralibs\bin\happy.exe is version 1.18.10
```
By using `cabal install happy` and some `PATH` manipulations, installation succeeded.
@capitanbatata thanks!

**Comment by mgajda** [comment]
I am afraid that is issue with `haskell-src-exts`. Sorry for that, but the right place to fix it is there: https://github.com/haskell-suite/haskell-src-exts/issues
